version: '3'

services:
  map-app:
    container_name: map-app
    build: .
    tty: true
    working_dir: /usr/src/map-app
    ports:
      - 8080:3000
    volumes:
      - .:/usr/src/map-app:cached
      - node_modules:/usr/src/map-app/node_modules
      - dist:/usr/src/map-app/dist

volumes:
  node_modules: {}
  dist: {}
